### ISSUE TITLE
RA

### ISSUE THREAD

**Issue by Rusttam** [isbendiyarovanezrin/PragmatechFrontendProject#1]
Menim birtanecik ablam,repona baxdim,commit sayi goze carpandir,folder readme-de cox goze batandir,lakin javascript papkalarinin icinde olan reqem adlandirmalarin beyenmedim,ve bir cox commitlerin ne etdiyinle bagli tam melumat vermir.Daha sonra etdiyin isler her ne qeder xirda isler olasada,mence iwliyib qoymagin yaxwidi,ki inaniram ki gun be gun dahada agirlarina kececeksen inWAllah.Biraz commit adlarina daha ustunluk versen ela olacaq.Ve readme hissesinde mence cox abartili elemisen,misal ucun orda link olaraq yazdigin meqaleleri yada gorduyun agir application-larida qoyabilersen,yenede meslehet senindir.

**Comment by isbendiyarovanezrin** [comment]
Təşəkkür edirəm.
